# Jaggernaut Event Plugin
# Plugin is meant to be used on The Plonk SMP on a Standalone Server

# Waiting Arena Location
waiting arena location: {world: spawn, x: 3, y: 60, z: 100, yaw: 0, pitch: 0}
# PvP Arena Settings
pvp arena:
  # Spawn Location
  spawn location: {world: spawn, x: 3, y: 60, z: 100, yaw: 0, pitch: 0}
countdown:
  # Countdown Time
  # When someone runs /event start, it will teleport them to the PvP Arena, though they won't be able to move
  # Until the timer is started.

  # Time in seconds
  time: 60
  # Notify at (When to notify for countdown, all numbers must be less than or equal to time otherwise error, and greater than 0).
  notify at: [60, 30, 10, 5, 3, 2, 1]
# Indexes 0 through 8 refer to the hotbar. 9 through 35 refer to the main inventory, counting up from 9 at the top
# left corner of the inventory, moving to the right, and moving to the row below it back on the left side when it
# reaches the end of the row. It follows the same path in the inventory like you would read a book.
#
# Indexes 36 through 39 refer to the armor slots. Index 40 refers to the off hand (shield) item slot.
# Refer to the below example on how to make items
items:
  juggernaut:
    - type: DIAMOND_HELMET
      slot: 39
      display-name: Cool Armor
      flags:
        # The enchantment uses vanilla enchantment names.
        # You can have enchantment levels that are not vanilla (32,767 is the max)
        enchantments:
          UNBREAKING: 1
    - type: SPLASH_POTION
      slot: 0
      flags:
        # The potion system is strictly vanilla! You can not have
        # non-vanilla settings here. Please check creative inventory
        # for more info.
        #
        # For example, INSTANT_HEAL does not have an extended version
        # Setting to true will cause an error.
        potion:
          effect: INSTANT_HEAL
          extended: false
          upgraded: false

  normal:
    - slot: 5
      type: LEATHER_HELMET

# Set messages for the plugin
# You can documentation for the message system here: https://docs.adventure.kyori.net/minimessage.html
#
# All messages can either be one line or multi-line. You can always change anything.
#
# Single Line:
# key: "value"
#
# Multi Line:
# key: |-
#   value line 1
#   value line 2
messages:
  # Displayed when invalid argument or /event help. This message has no placeholders.
  help: |-

    <dark_gray><strikethrough><bold>                 [<reset>  <yellow><bold>JUGGERNAUT EVENT  <dark_gray><strikethrough><bold>]                 <reset>

    <gray>() Required | [] Optional

    <yellow>/event help <dark_gray>- <gray>Shows this message
    <yellow>/event start (duration) [player] <dark_gray>- <gray>Starts the event
    <yellow>/event reload <dark_gray>- <gray>Reloads the configuration.
    <yellow>/event cancel <dark_gray>- <gray>Cancels an event

    <dark_gray><strikethrough><bold>                 [<reset>  <yellow><bold>JUGGERNAUT EVENT  <dark_gray><strikethrough><bold>]                 <reset>
    <reset>
  # Displayed when player has no permission. This message has no placeholders.
  no permission: "<red>You don't have permission to run this command!"
  # Displayed when sender reloads plugin. This message has no placeholders.
  reload: "<yellow>Plugin reloaded. Check console for possible issues."
  # Displayed to all players while game is not running on action bar. This message has no placeholders.
  action bar awaiting: "<red><bold>AWAITING EVENT START"
  # Displayed as countdown until event started. Please looked at the "notify at" key under
  # the "countdown" section to set notify times.
  #
  # Placeholders:
  # <secondsleft> - Returns the seconds left for the countdown
  reminder event start: "<yellow>There are <gold><secondsleft> <yellow>until the event starts!"
  # Displayed as countdown until event started. The intervals are ALWAYS
  # 60 seconds, 30, 15, 10, 5, 4, 3, 2, 1. These intervals can not be changed. This message has no placeholders.
  reminder event end: "<yellow>There are <gold><secondsleft> <yellow>until the event ends!"
  # Displayed when random juggernaut picked.
  # Placeholders:
  # <name> - Returns the name of the Juggernaut
  juggernaut random: |-
    <reset>
    <gold><name> <yellow>is now the randomly picked juggernaut!
    <reset>
  # Displayed when juggernaut is killed by player
  # Placeholders:
  # <killedplayer> - Returns the old juggernaut
  # <juggernaut> - Returns the new juggernaut
  juggernaut kill change player: |-
    <reset>
    <gold><killedplayer> <yellow>was killed by <gold><juggernaut><yellow>. <gold><juggernaut> <yellow>is now the Juggernaut!
    <reset>
  # Displayed when juggernaut is specified. (i.e. /event start Intriguing) and not random.
  # <name> - Returns the name of the Juggernaut
  juggernaut not random: |-
    <reset>
    <gold><name> <yellow>is now the juggernaut!
    <reset>
  # Displayed when too many people log out and only left with one player.
  # This message has no placeholders.
  cannot continue not enough players: "<red>We can no longer continue the event, there
    were enough players!"
  # Displayed when game ends and someone has won.
  # Placeholders:
  # <name> - Returns the name of the winner
  announce winner: |-
    <reset>
    <gold><name> <yellow>has won the event. <gold><bold>CONGRATULATIONS!
    <reset>
  # Displayed when game is set to end, everyone is teleported to lobby, etc. This message has no placeholders
  ending event: "<yellow>Ending the Juggernaut Event!"
  # Displayed when user provides invalid time. This message has no placeholders.
  invalid time provided: "<red>You provided an invalid time!"
  # Displayed when user successfully starts game. This message has no placeholders.
  successful start event: "<red>You successfully started the Juggernaut event."
  # Displayed when user runs /event cancel. This message has no placeholders.
  successful stop: "<yellow>You successfully stopped the Juggernaut event!"
  # Displayed when user providers invalid player. This message has no placeholders.
  invalid player: "<red>You provided an invalid player!"
  # Displayed when event is already running. This message has no placeholders.
  event already running: "<red>An event is already running!"
  # Displayed when /event cancel is used. This message has no placeholders.
  forced stopped: "<red>Event was forced stopped!"
  # Displayed when exempt players try to kill player. This message has no placeholders.
  cant hit players: "<red>You can't hit players, you are an exempt player!"
  # Displayed when exempt player is tried to used as a player in /event start <player>. This message has no placeholders.
  invalid player exempt: "<red>Invalid Player. This player is exempt."
  # Displayed when not enough players sent to admin with /event start. This message has no placeholders.
  not enough players: "<red>There are not enough players. There must be at least 2
    non-exempt players!"
  # Displayed when /event cancel is ran, and event is not running.
  event not running: "<red>No event is currently running!"
  # Placeholder tag for %juggernautevent_tag%
  normal tag: '<dark_gray><bold>[<aqua><bold>NORMAL<dark_gray><bold>]<aqua> '
  # Placeholder tag for %juggernautevent_tag%
  juggernaut tag: '<dark_gray><bold>[<red><bold>JUGGERNAUT<dark_gray><bold>]<red> '




