# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build Development JAR

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "<version>.*<\/version>"
        replace: "<version>DEV-BUILD (COMMIT ID: ${git.commit.id.describe-short})"
        include: "pom.xml"
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: mvn clean package
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Juggernaut Event Development Build"
        files: |
          target/JuggernautEvent.jar
