# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build JAR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v18
      with:
        mirrors: >
          [
            {
              "id": "maven-shade-plugin",
              "mirrorOf": "external:http:*",
              "url": "http://repository.apache.org/snapshots/"
            }
          ]
        output_file: .m2/settings.xml
    - name: Build with Maven
      run: mvn clean package
    - name: Plugin JAR
      uses: actions/upload-artifact@v2
      with:
        name: KillTheJuggernaut Artifacts
        path: target/**.jar
